/* tslint:disable */
/* eslint-disable */
/**
 * Simple Kanban API
 * A simple kanban API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BoardInCreate
 */
export interface BoardInCreate {
    /**
     * 
     * @type {string}
     * @memberof BoardInCreate
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof BoardInCreate
     */
    description?: string;
}

/**
 * Check if a given object implements the BoardInCreate interface.
 */
export function instanceOfBoardInCreate(value: object): value is BoardInCreate {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function BoardInCreateFromJSON(json: any): BoardInCreate {
    return BoardInCreateFromJSONTyped(json, false);
}

export function BoardInCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoardInCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function BoardInCreateToJSON(json: any): BoardInCreate {
    return BoardInCreateToJSONTyped(json, false);
}

export function BoardInCreateToJSONTyped(value?: BoardInCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
    };
}

