/* tslint:disable */
/* eslint-disable */
/**
 * Simple Kanban API
 * A simple kanban API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LabelInUpdate } from './LabelInUpdate';
import {
    LabelInUpdateFromJSON,
    LabelInUpdateFromJSONTyped,
    LabelInUpdateToJSON,
    LabelInUpdateToJSONTyped,
} from './LabelInUpdate';

/**
 * 
 * @export
 * @interface BoardInUpdate
 */
export interface BoardInUpdate {
    /**
     * 
     * @type {string}
     * @memberof BoardInUpdate
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BoardInUpdate
     */
    description?: string | null;
    /**
     * 
     * @type {Array<LabelInUpdate>}
     * @memberof BoardInUpdate
     */
    labels?: Array<LabelInUpdate> | null;
}

/**
 * Check if a given object implements the BoardInUpdate interface.
 */
export function instanceOfBoardInUpdate(value: object): value is BoardInUpdate {
    return true;
}

export function BoardInUpdateFromJSON(json: any): BoardInUpdate {
    return BoardInUpdateFromJSONTyped(json, false);
}

export function BoardInUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoardInUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'labels': json['labels'] == null ? undefined : ((json['labels'] as Array<any>).map(LabelInUpdateFromJSON)),
    };
}

export function BoardInUpdateToJSON(json: any): BoardInUpdate {
    return BoardInUpdateToJSONTyped(json, false);
}

export function BoardInUpdateToJSONTyped(value?: BoardInUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'labels': value['labels'] == null ? undefined : ((value['labels'] as Array<any>).map(LabelInUpdateToJSON)),
    };
}

