/* tslint:disable */
/* eslint-disable */
/**
 * Simple Kanban API
 * A simple kanban API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CardColumn = {
    Backlog: 'BACKLOG',
    Todo: 'TODO',
    Doing: 'DOING',
    Done: 'DONE'
} as const;
export type CardColumn = typeof CardColumn[keyof typeof CardColumn];


export function instanceOfCardColumn(value: any): boolean {
    for (const key in CardColumn) {
        if (Object.prototype.hasOwnProperty.call(CardColumn, key)) {
            if (CardColumn[key as keyof typeof CardColumn] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CardColumnFromJSON(json: any): CardColumn {
    return CardColumnFromJSONTyped(json, false);
}

export function CardColumnFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardColumn {
    return json as CardColumn;
}

export function CardColumnToJSON(value?: CardColumn | null): any {
    return value as any;
}

export function CardColumnToJSONTyped(value: any, ignoreDiscriminator: boolean): CardColumn {
    return value as CardColumn;
}

