/* tslint:disable */
/* eslint-disable */
/**
 * Simple Kanban API
 * A simple kanban API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LabelColor } from './LabelColor';
import {
    LabelColorFromJSON,
    LabelColorFromJSONTyped,
    LabelColorToJSON,
    LabelColorToJSONTyped,
} from './LabelColor';

/**
 * 
 * @export
 * @interface LabelInUpdate
 */
export interface LabelInUpdate {
    /**
     * 
     * @type {LabelColor}
     * @memberof LabelInUpdate
     */
    color: LabelColor;
    /**
     * 
     * @type {string}
     * @memberof LabelInUpdate
     */
    name?: string | null;
}



/**
 * Check if a given object implements the LabelInUpdate interface.
 */
export function instanceOfLabelInUpdate(value: object): value is LabelInUpdate {
    if (!('color' in value) || value['color'] === undefined) return false;
    return true;
}

export function LabelInUpdateFromJSON(json: any): LabelInUpdate {
    return LabelInUpdateFromJSONTyped(json, false);
}

export function LabelInUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): LabelInUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'color': LabelColorFromJSON(json['color']),
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function LabelInUpdateToJSON(json: any): LabelInUpdate {
    return LabelInUpdateToJSONTyped(json, false);
}

export function LabelInUpdateToJSONTyped(value?: LabelInUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'color': LabelColorToJSON(value['color']),
        'name': value['name'],
    };
}

