/* tslint:disable */
/* eslint-disable */
/**
 * Simple Kanban API
 * A simple kanban API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LabelColor } from './LabelColor';
import {
    LabelColorFromJSON,
    LabelColorFromJSONTyped,
    LabelColorToJSON,
    LabelColorToJSONTyped,
} from './LabelColor';

/**
 * 
 * @export
 * @interface LabelInCreate
 */
export interface LabelInCreate {
    /**
     * 
     * @type {LabelColor}
     * @memberof LabelInCreate
     */
    color: LabelColor;
    /**
     * 
     * @type {string}
     * @memberof LabelInCreate
     */
    name?: string;
}



/**
 * Check if a given object implements the LabelInCreate interface.
 */
export function instanceOfLabelInCreate(value: object): value is LabelInCreate {
    if (!('color' in value) || value['color'] === undefined) return false;
    return true;
}

export function LabelInCreateFromJSON(json: any): LabelInCreate {
    return LabelInCreateFromJSONTyped(json, false);
}

export function LabelInCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): LabelInCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'color': LabelColorFromJSON(json['color']),
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function LabelInCreateToJSON(json: any): LabelInCreate {
    return LabelInCreateToJSONTyped(json, false);
}

export function LabelInCreateToJSONTyped(value?: LabelInCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'color': LabelColorToJSON(value['color']),
        'name': value['name'],
    };
}

