/* tslint:disable */
/* eslint-disable */
/**
 * Simple Kanban API
 * A simple kanban API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LabelColor } from './LabelColor';
import {
    LabelColorFromJSON,
    LabelColorFromJSONTyped,
    LabelColorToJSON,
    LabelColorToJSONTyped,
} from './LabelColor';

/**
 * 
 * @export
 * @interface LabelOut
 */
export interface LabelOut {
    /**
     * 
     * @type {LabelColor}
     * @memberof LabelOut
     */
    color: LabelColor;
    /**
     * 
     * @type {string}
     * @memberof LabelOut
     */
    name: string;
}



/**
 * Check if a given object implements the LabelOut interface.
 */
export function instanceOfLabelOut(value: object): value is LabelOut {
    if (!('color' in value) || value['color'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function LabelOutFromJSON(json: any): LabelOut {
    return LabelOutFromJSONTyped(json, false);
}

export function LabelOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): LabelOut {
    if (json == null) {
        return json;
    }
    return {
        
        'color': LabelColorFromJSON(json['color']),
        'name': json['name'],
    };
}

export function LabelOutToJSON(json: any): LabelOut {
    return LabelOutToJSONTyped(json, false);
}

export function LabelOutToJSONTyped(value?: LabelOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'color': LabelColorToJSON(value['color']),
        'name': value['name'],
    };
}

