/* tslint:disable */
/* eslint-disable */
/**
 * Simple Kanban API
 * A simple kanban API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserOutPublic
 */
export interface UserOutPublic {
    /**
     * 
     * @type {number}
     * @memberof UserOutPublic
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UserOutPublic
     */
    email: string;
}

/**
 * Check if a given object implements the UserOutPublic interface.
 */
export function instanceOfUserOutPublic(value: object): value is UserOutPublic {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function UserOutPublicFromJSON(json: any): UserOutPublic {
    return UserOutPublicFromJSONTyped(json, false);
}

export function UserOutPublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserOutPublic {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
    };
}

export function UserOutPublicToJSON(json: any): UserOutPublic {
    return UserOutPublicToJSONTyped(json, false);
}

export function UserOutPublicToJSONTyped(value?: UserOutPublic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
    };
}

