/* tslint:disable */
/* eslint-disable */
/**
 * Simple Kanban API
 * A simple kanban API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserInSearch
 */
export interface UserInSearch {
    /**
     * 
     * @type {string}
     * @memberof UserInSearch
     */
    email: string;
}

/**
 * Check if a given object implements the UserInSearch interface.
 */
export function instanceOfUserInSearch(value: object): value is UserInSearch {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function UserInSearchFromJSON(json: any): UserInSearch {
    return UserInSearchFromJSONTyped(json, false);
}

export function UserInSearchFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInSearch {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function UserInSearchToJSON(json: any): UserInSearch {
    return UserInSearchToJSONTyped(json, false);
}

export function UserInSearchToJSONTyped(value?: UserInSearch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

