/* tslint:disable */
/* eslint-disable */
/**
 * Simple Kanban API
 * A simple kanban API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserInUpdate
 */
export interface UserInUpdate {
    /**
     * 
     * @type {string}
     * @memberof UserInUpdate
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserInUpdate
     */
    password?: string | null;
}

/**
 * Check if a given object implements the UserInUpdate interface.
 */
export function instanceOfUserInUpdate(value: object): value is UserInUpdate {
    return true;
}

export function UserInUpdateFromJSON(json: any): UserInUpdate {
    return UserInUpdateFromJSONTyped(json, false);
}

export function UserInUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function UserInUpdateToJSON(json: any): UserInUpdate {
    return UserInUpdateToJSONTyped(json, false);
}

export function UserInUpdateToJSONTyped(value?: UserInUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

