/* tslint:disable */
/* eslint-disable */
/**
 * Simple Kanban API
 * A simple kanban API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserInCreate
 */
export interface UserInCreate {
    /**
     * 
     * @type {string}
     * @memberof UserInCreate
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserInCreate
     */
    password: string;
}

/**
 * Check if a given object implements the UserInCreate interface.
 */
export function instanceOfUserInCreate(value: object): value is UserInCreate {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function UserInCreateFromJSON(json: any): UserInCreate {
    return UserInCreateFromJSONTyped(json, false);
}

export function UserInCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function UserInCreateToJSON(json: any): UserInCreate {
    return UserInCreateToJSONTyped(json, false);
}

export function UserInCreateToJSONTyped(value?: UserInCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

