/* tslint:disable */
/* eslint-disable */
/**
 * Simple Kanban API
 * A simple kanban API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserOut
 */
export interface UserOut {
    /**
     * 
     * @type {number}
     * @memberof UserOut
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UserOut
     */
    email: string;
    /**
     * 
     * @type {Date}
     * @memberof UserOut
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserOut
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the UserOut interface.
 */
export function instanceOfUserOut(value: object): value is UserOut {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function UserOutFromJSON(json: any): UserOut {
    return UserOutFromJSONTyped(json, false);
}

export function UserOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function UserOutToJSON(json: any): UserOut {
    return UserOutToJSONTyped(json, false);
}

export function UserOutToJSONTyped(value?: UserOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

