services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: kanban
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d kanban"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: skppy/simple-kanban-server:latest
    environment:
      SECRET_KEY: e022b6e22b2f42ae5e1d77194a0aac4ff16e47090ac2fd15e15926e3761c2773
      ALGORITHM: HS256
      DB_URL: postgresql://admin:admin@db:5432/kanban
      POPULATE_DB: TRUE
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: 