name: Deploy MCP

on:
  push:
    branches: [main]
    paths:
      - "mcp/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push mcp
        uses: docker/build-push-action@v5
        with:
          context: ./mcp
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kanban-mcp:latest
